# pycharm.yml
---

# https://github.com/Oefenweb/ansible-pycharm

- name: create (download) directory
  become: yes
  become_user: "{{ general.user }}"
  file:
    path: "{{ pycharm_downloads_path }}"
    state: directory
  tags:
    - configuration
    - pycharm
    - pycharm-download

- name: download
  become: yes
  become_user: "{{ general.user }}"
  get_url:
    url: "http://download.jetbrains.com/python/pycharm-{{ pycharm_edition }}-{{ pycharm_version }}.tar.gz"
    dest: "{{ pycharm_downloads_path }}/pycharm-{{ pycharm_edition }}-{{ pycharm_version }}.tar.gz"
  tags:
    - configuration
    - pycharm
    - pycharm-downloads

- name: create (install) directory
  become: yes
  become_user: "{{ general.user }}"
  file:
    path: "{{ pycharm_install_prefix }}"
    state: directory
  tags:
    - configuration
    - pycharm
    - pycharm-download

- name: install
  become: yes
  become_user: "{{ general.user }}"
  unarchive:
    src: "{{ pycharm_downloads_path }}/pycharm-{{ pycharm_edition }}-{{ pycharm_version }}.tar.gz"
    dest: "{{ pycharm_install_prefix }}"
    creates: "{{ pycharm_install_prefix }}/pycharm-{{ pycharm_version }}"
    copy: false
  tags:
    - configuration
    - pycharm
    - pycharm-install

- name: install shortcut
  become: yes
  become_user: "{{ general.user }}"
  template:
    src: "roles/pycharm/templates/PyCharmCE.desktop.j2"
    dest: "{{ general.home_dir }}/Desktop/PyCharmCE.desktop"
    owner: "{{ general.user }}"
    mode: 0755
  tags:
    - configuration
    - pycharm
    - pycharm-download

- name: create (pycharm options) directory
  become: yes
  become_user: "{{ general.user }}"
  file:
    # path: /home/{{ general.user }}/.PyCharmCE2016.3/config/options
    path: "{{ general.home_dir }}/.PyCharmCE{{ pycharm_major_release }}/config/options"
    state: directory
  tags:
    - configuration
    - pycharm
    - pycharm-download

- name: install basic configuration
  become: yes
  become_user: "{{ general.user }}"
  template:
    src: "roles/pycharm/templates/options.xml.j2"
    # dest: /home/{{ general.user }}/.PyCharmCE2016.3/config/options/options.xml
    dest: "{{ general.home_dir }}/.PyCharmCE{{ pycharm_major_release }}/config/options/options.xml"
    owner: "{{ general.user }}"
    mode: 0644
  tags:
    - configuration
    - pycharm
    - pycharm-download
