# vagrant.yml
---
- name: add epel repo
  become: yes
  become_user: "{{ general.user }}"
  yum:
    name: epel-release
    state: present
  tags:
    - configuration
    - openconnect

- name: install
  become: yes
  become_user: "{{ general.user }}"
  yum:
    name: "openconnect"
    state: latest
  tags:
    - configuration
    - openconnect
