---
- name: Install epel repository
  yum:
    name: epel-release
    state: latest

- name: Install XRDP
  yum: 
    name: xrdp
    state: latest 

- name: Install TigerVNC Server
  yum: 
    name: tigervnc-server
    state: latest

- name: Start XRDP 
  service: 
    name: xrdp
    state: started
    enabled: yes 

- name: Allow XRDP Inbound 
  firewalld: 
    zone: public
    port: 3389/tcp
    state: enabled
    permanent: true

- name: Restart firewalld
  service:
    name: firewalld
    state: reloaded
