# python3_install.yml
- name: Install IUM Repo
  become: yes
  yum: name={{ item }} state=latest
  ignore_errors: true
  with_items:
    - https://centos7.iuscommunity.org/ius-release.rpm

# python3_install.yml
- name: Install Python 3.6 via IUM
  become: yes
  yum: name={{ item }} state=latest
  with_items:
    - python36u
    - python27u
